### ISSUE TITLE
Rootless containers support status?

### ISSUE THREAD

**Issue by alexandresoro** [hotio/sonarr#15]
Hello,

I am trying to test the image using `podman` running with my own user account (i.e. not root on the host).
What I would like to achieve is that the files that are downloaded should be moved to a given folder.
This folder is mapped to a host folder via a volume.
This is working fine, however as rootless containers rely on `subuid` and `subgid`, the files/folders are mapped to a given ‘virtual’ user on the host.
I’d like to be able to have these files/folders to be owned by myself, the one user running the container.

To do this, what would be needed is to be able to run the container with `PUID=0` and `PGID=0` so that the files are correctly owned by me on the host. In rootless containers, `ID=0` is mapped to the user that started the container and `ID>0` are mapped to this user subid’s that have no real existence on the host - they are basic IDs.

Such thing is not possible today as per https://github.com/hotio/sonarr/blob/release/root/etc/cont-init.d/00-start-container
 that checks if a container is run with `PUID/PGID = 0`.

I understand the rationale of this: to prevent the default docker instance where the daemon run as root, but this use case would be valid in case of rootless containers, without compromising the security of the host.

Is there any way to achieve this while using the image, or is this something that should be improved?

Thanks

**Comment by mrhotio** [comment]
you're probably better of with these images if they are still maintained https://github.com/itscontained/docker/tree/master/images

**Comment by onedr0p** [comment]
@mrhotio those were moved to the k8s-at-home org.

https://github.com/k8s-at-home/container-images

**Comment by alexandresoro** [comment]
Hi @onedr0p, thanks for sharing! One think leading to another, I finally took the opportunity to migrate to k3s using your images!

**Comment by onedr0p** [comment]
@alexandresoro feel free to join us on discord at https://discord.gg/k8s-at-home :)

**Comment by LegitGreenBoi** [comment]
> @mrhotio @alexandresoro those were moved to the k8s-at-home org which still keep rootless in mind.
> 
> https://github.com/k8s-at-home/container-images

I'm interested in this container, but the link you posted isn't available anymore.

Is this the current repository now?
https://github.com/onedr0p/containers

**Comment by onedr0p** [comment]
Yes, that's the containers I use and support.
