### ISSUE TITLE
Free space being calculated wrong

### ISSUE THREAD

**Issue by alanshelley** [hotio/sonarr#16]
Running Unraid 6.9.2 and latest Sonarr image. Having an issue with the free space calculation in Sonarr.

Under System > Status my disk space is shown as:

<img width="1197" alt="Screen Shot 2022-01-22 at 19 40 30" src="https://user-images.githubusercontent.com/4118123/150660127-0513d9b3-70f5-40a8-8c35-2bccb44197a0.png">

This calculation is (seemingly) based on my free space available in my Docker image, which is correct and consistent with your Radarr image. The Location as / (/) is odd and inconsistent with your Radarr image:

<img width="1204" alt="Screen Shot 2022-01-22 at 19 46 49" src="https://user-images.githubusercontent.com/4118123/150660254-652bf1f5-527a-4627-8782-e09bd0d224f4.png">

Under Settings > Media Management  my free space is shown as:

<img width="1212" alt="Screen Shot 2022-01-22 at 19 39 36" src="https://user-images.githubusercontent.com/4118123/150660106-65bb82a0-56f4-45e4-9ae7-0bb770ef5680.png">

This is also seemingly based on my Docker image free space rather than my array free space. This is not consistent with your Radarr image, which displays my root folder and the free space of my array:

<img width="1196" alt="Screen Shot 2022-01-22 at 19 47 36" src="https://user-images.githubusercontent.com/4118123/150660270-3f118fe9-8523-436c-883a-3a5e30f8483f.png">

My mount point for both are identical:

/config > /mnt/user/appdata/(radarr/sonarr)
/data > /mnt/user/   (this is the main directory for all shares)

I have installed other Sonarr containers and they all passthrough the array size properly with the same mount points. I have also installed the hotio-Sonarr image again to start from scratch and right from the start it was displaying the / (/) Location and the wrong free space under Media Management. I have also tried changing the mount points for the root folder to see if it was the issue, but the problem persisted. 

I ran into an issue while importing some large episode files that were larger than my (at the time) calculated free space leading me to have to expand my docker image to 75GB.

**Comment by mrhotio** [comment]
known issue regarding mono on alpine iirc, can't do much about it
